services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_GOOGLE_AUTH_URL: ${VITE_GOOGLE_AUTH_URL}
        VITE_GOOGLE_AUTH_PATH: ${VITE_GOOGLE_AUTH_PATH}
        VITE_APP_HOME_PATH: ${VITE_APP_HOME_PATH}
        VITE_RESET_PASSWORD_PATH: ${VITE_RESET_PASSWORD_PATH}
        VITE_OAUTH_CALLBACK_PATH: ${VITE_OAUTH_CALLBACK_PATH}
        VITE_PUBLIC_LOGO_PATH: ${VITE_PUBLIC_LOGO_PATH}
        VITE_RESET_PASSWORD_ENDPOINT: ${VITE_RESET_PASSWORD_ENDPOINT}
        VITE_CONTACT_EMAIL: ${VITE_CONTACT_EMAIL}
        VITE_GITHUB_REPO_URL: ${VITE_GITHUB_REPO_URL}
        VITE_LINKEDIN_URL: ${VITE_LINKEDIN_URL}
    ports:
      - "5173:80"
    restart: unless-stopped
