FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

ARG VITE_API_BASE_URL
ARG VITE_GOOGLE_AUTH_URL
ARG VITE_GOOGLE_AUTH_PATH
ARG VITE_APP_HOME_PATH
ARG VITE_RESET_PASSWORD_PATH
ARG VITE_OAUTH_CALLBACK_PATH
ARG VITE_PUBLIC_LOGO_PATH
ARG VITE_RESET_PASSWORD_ENDPOINT
ARG VITE_CONTACT_EMAIL
ARG VITE_GITHUB_REPO_URL
ARG VITE_LINKEDIN_URL

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_GOOGLE_AUTH_URL=$VITE_GOOGLE_AUTH_URL
ENV VITE_GOOGLE_AUTH_PATH=$VITE_GOOGLE_AUTH_PATH
ENV VITE_APP_HOME_PATH=$VITE_APP_HOME_PATH
ENV VITE_RESET_PASSWORD_PATH=$VITE_RESET_PASSWORD_PATH
ENV VITE_OAUTH_CALLBACK_PATH=$VITE_OAUTH_CALLBACK_PATH
ENV VITE_PUBLIC_LOGO_PATH=$VITE_PUBLIC_LOGO_PATH
ENV VITE_RESET_PASSWORD_ENDPOINT=$VITE_RESET_PASSWORD_ENDPOINT
ENV VITE_CONTACT_EMAIL=$VITE_CONTACT_EMAIL
ENV VITE_GITHUB_REPO_URL=$VITE_GITHUB_REPO_URL
ENV VITE_LINKEDIN_URL=$VITE_LINKEDIN_URL

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
